package com.mindtree.Exception;



public class Main {
	public void x() throws MyException {
		
		throw new ArithmeticException();
	}
	
	public void y() throws MyException {
		
		try{
			x();
		}catch(MyException e){
			throw new MyException(e.getMessage(), e.getCause());
		}
		
	}
	public void z() {
		try {
			y();
		} catch(MyException e) {
			System.err.println("xhjvc");
		}
	}

	public static void main(String[] args) {
		Main obj = new Main();
		obj.z();
	}

}
